### ISSUE TITLE
listview-fullscreen sample app got crash when I try to reproduce full screen

### ISSUE THREAD

**Issue by emretekin** [jwplayer/jwplayer-android-best-practice-apps#14]
I think you guys need to update listview-fullscreen sample. Cause it crashed unfortunately.

By the way,  this sample app use listview but I want to set on recyclerview. 

And I want to hide full screen button on player view for temporary solution. 
How can I hide this button ?

**Comment by GMSyrimis** [comment]
We have updated demos for both ListView and RecyclerView. Closing this thread as it's fairly old
