### ISSUE TITLE
live streaming rewind

### ISSUE THREAD

**Issue by bitamirshafiee** [jwplayer/jwplayer-android-best-practice-apps#16]
Hi after version 8 I can use live streaming rewind, one of your colleagues said that it a bug in version 8.
now I want to upgrade to version 8 to take advantage of ads but there is no way.
it's months I'm waiting for it, but no response

**Comment by GMSyrimis** [comment]
Hi, if you haven't resolved this issue already please reach out to support. I'm closing this thread as it's fairly old.
