### ISSUE TITLE
com.google.android.libraries.cast.companionlibrary.cast.exceptions.TransientNetworkDisconnectionException

### ISSUE THREAD

**Issue by yokei15** [jwplayer/jwplayer-android-best-practice-apps#2]
After building the sdk and run it these error occurs 

**Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> java.lang.ClassNotFoundException: com.google.android.libraries.cast.companionlibrary.cast.exceptions.TransientNetworkDisconnectionException**

Can any one help me ??
Thanks in advance

**Comment by RikHeijdens** [comment]
Hi @yokei15 

This is an issue with Instant Run.

Please disable Instant Run and try building then.
You can install Instant Run on Linux / OS X by going to File/Apple Icon -> Preferences -> Build, Execution, Deployment -> Instant Run. Uncheck Enable Instant run.

Please let me know if that solves your problem.

**Comment by mostafazakaria** [comment]
Hi @RikHeijdens It worked after disabling InstantRun, I tried to integrate CastCompanionLibrary and this issue happened https://github.com/jwplayer/jwplayer-sdk-android-demo/issues/12
any solution for this problem it is not possible for me to disable Instant Run?

**Comment by RikHeijdens** [comment]
@mostafazakaria Did you try adding:

```groovy
packagingOptions {
    exclude 'jsr305_annotations/Jsr305_annotations.gwt.xml'
}
```

to your build.gradle files? Are you still seeing issues after adding that?
If you are still seeing issues, could you open another issue and post steps to reproduce and the stacktrace?

**Comment by mostafazakaria** [comment]
@RikHeijdens issue fixed with packagingOptions.
Thanks
