### ISSUE TITLE
Issue while changing the action(Play, Pause) from notification in case of multiple players are initialized

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [jwplayer/jwplayer-android-best-practice-apps#30]
Two-Player has been initialize in the application. Let say one is video and another one is Audio. Both the player is having playlist(let say 10 items). Now video player is paused and Audio player is playing audio. now at same time notification is not updating content and also when i tap on play button from notification it play video not audio and some time it will not respond any thing.

it works with one player intilization but not work with both player working in sync mode like one is playing and other is pause or vice versa.

It happen with android device with having JWplayer version **3.9.0**

**Comment by bluelabeldeveloper1** [comment]
Any updates here?

**Comment by GMSyrimis** [comment]
Hi, if you're still having this issue please contact support as they can help you troubleshoot this issue. I'm closing this thread as it's fairly old.
