### ISSUE TITLE
Does JW player v4 Support WebVTT Subtitle?

### ISSUE THREAD

**Issue by pavan555** [jwplayer/jwplayer-android-best-practice-apps#429]
I am using jw player v4 , i think this is awesome, but there is some feature missing.
captions are not working with webvtt or srt in v4 showing error invalid index/ invalid timing.
but it works well with v3 of jwplayer.

**Comment by GMSyrimis** [comment]
Hi, as mentioned on the other repo, please contact support about this if you're still having trouble. Overall, V4 supports both SRT and VTT captions
