### ISSUE TITLE
jCenter migration

### ISSUE THREAD

**Issue by SiarheiSm** [jwplayer/jwplayer-android-best-practice-apps#528]
https://github.com/jwplayer/jwplayer-sdk-android-demo/issues/112

com.jwplayer:jwplayer-core:4.2.0
> Could not resolve com.android.volley:volley:1.1.1.

seems in maven only versions 1.2.1 + available

**Comment by GMSyrimis** [comment]
If you update to 4.3.0 and you should be good to go. 👍 

Closing this as I can confirm this is no longer an issue, after updating the imports of the Best Practice Apps. If you run into any trouble please reach out to our support team and they can help you troubleshoot the issue
