### ISSUE TITLE
JWplayer on Android TV not responding to remote control buttons( play,pause, dpad etc)

### ISSUE THREAD

**Issue by HassanImtiaz** [jwplayer/jwplayer-android-best-practice-apps#571]
Hi,

I have integrated the latest Jwplayer 4.3.0 version in my tv app, video plays fine but player is not responsive to remote control actions. 

I did notice that for version 3.20.1 its working fine.

**Comment by GMSyrimis** [comment]
Hi, we did not implement support for TV apps yet. You'll have to manage key inputs on your end and possibly drive a custom UI to get what you're looking for with V4. There may be some news on TV support in the future though ;)

**Comment by HassanImtiaz** [comment]
Thank you for your response, for 3.20.1 controls respond however I don't see any highlighter for selector. Like when I navigate from dpad the specific buttons (i.e pause,play & rewind) dont draw a highlighter around it. Do I need to do anything extra for tv support? 
Also is there a way to hide/show specific buttons.

**Comment by GMSyrimis** [comment]
@HassanImtiaz The 3.x version of our SDK uses a webview as the UI. So you would use CSS to render focus changes. Same goes for showing or hiding buttons.
