### ISSUE TITLE
Jwplayer Live Stream Stuck

### ISSUE THREAD

**Issue by HassanImtiaz** [jwplayer/jwplayer-android-best-practice-apps#664]
We are using jwplayer version : 4.4.0. We play a live stream from url(m3u8 format).

There is a strange issue that player frequently stucks on loading, means onBuffer event is called but after that it keeps on spinning & nothing happens.

onError method is never called & there isn't any info available in logs as-well.

What are the options available to identify the route cause? We have noticed that stream works just fine on other platforms that are not using jwplayer.

**Comment by GMSyrimis** [comment]
Hi, it sounds like the live window is very short so the player is running out of content before the new window is downloaded. I'd recommend contacting our support team to better troubleshoot this issue.
