### ISSUE TITLE
 [GoogleDAIDemo] Preroll restarts when device is rotated

### ISSUE THREAD

**Issue by katjarutnik** [jwplayer/jwplayer-android-best-practice-apps#688]
Trying out the GoogleDAIDemo, I noticed that preroll restarts playing when device is rotated.

Expected result: ad does not restart when device orientation is changed

**Comment by ceberm** [comment]
Hi @katjarutnik I think this is solved on the latest version, I am not seeing the issue

**Comment by Jmilham21** [comment]
Hi @katjarutnik, this is related to the configuration of the demo app here. This app and activity are not designed to persist through the orientation change, and the activity is being restarted (causing the player to destroy and set back up). 

This is described [here](https://developer.jwplayer.com/jwplayer/docs/android-configure-the-manifest) and can be seen in other best practice applications in this repo. 

I do believe @ceberm is correct about there being a bug in earlier versions but as of 4.6.0 this should be resolved.
