### ISSUE TITLE
Calling .closeRelatedOverlay() or .openRelatedOverlay() returns Uncaught TypeError

### ISSUE THREAD

**Issue by katjarutnik** [jwplayer/jwplayer-android-best-practice-apps#690]
I am using JW Android SDK 4.6.0.

Calling player.openRelatedOverlay():
`I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: relatedPlugin.open is not a function", source: https://intercept.jw/assets/jwplayer/jwplayer_container_debug.html (1)`

Calling player.closeRelatedOverlay():
`I/chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: relatedPlugin.close is not a function", source: https://intercept.jw/assets/jwplayer/jwplayer_container_debug.html (1)
`

Expected result: related overlay either opens or closes, but it doesn't seem to work. 

Does anyone know why?

**Comment by Jmilham21** [comment]
@katjarutnik this is on our radar already. You can keep an eye on release notes [here](https://releases.jwplayer.com/android-sdk/) for upcoming releases that may include this fix. 

If you require more direct updates, please reach out to our support team and open a case.
