### ISSUE TITLE
JWPlayer Player show black bars on Right Side of the Screen

### ISSUE THREAD

**Issue by frared358** [jwplayer/jwplayer-android-best-practice-apps#692]
JWPlayer Player show black bars on Left side of the videos when we do Full screen on high resolution devices
please help me with this

**Kotlin code for FullScreen & Aspect Ratio**
`val isFull = mPlayer!!.fullscreen`
`mPlayer!!.setFullscreen(!isFull, true)`

refer image

![WhatsApp Image 2022-10-02 at 6 36 38 PM](https://user-images.githubusercontent.com/28569625/193455953-857c6f75-ee86-458f-9158-327ac55e9a67.jpeg)

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
