### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by mancuk** [jwplayer/jwplayer-android-best-practice-apps#693]
how to auto play on android?

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

For questions, please refer to our documentation or contact our support team.
