### ISSUE TITLE
Don't we need to dispose of player like the way we use Exoplayer?

### ISSUE THREAD

**Issue by brian-chu-twc** [jwplayer/jwplayer-android-best-practice-apps#699]
From the example and online document I don't see any must-do list of how to clean up jwplayer. Is that by design or something I have to dispose of? Sorry if this is an obvious question as I can't find any mention of it.

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket). 

We do not expose a destroy method by choice. We urge you to pass in a Lifecycle observer on player instantiation to allow for proper handling of the memory and player.
