### ISSUE TITLE
JWPlayer seek possition Issue

### ISSUE THREAD

**Issue by aliceLit** [jwplayer/jwplayer-android-best-practice-apps#715]
Using Jwplayer version  4.15.2 

The issue of moving seek position

mJWPlayer.getDuration()  always retun 0

mJWPlayer.getPosition()  always retun 0

 mJWPlayer.seek( n)  do not move seep / cursor

**Comment by aliceLit** [comment]
I made the same test for latest version and its not working.

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
