### ISSUE TITLE
Issue : JWPlayer Caption Size  android sdk version 4.15.2 

### ISSUE THREAD

**Issue by aliceLit** [jwplayer/jwplayer-android-best-practice-apps#716]
Caption size in portrait screen orientation is big, in relation to horizontal 
The captions  take hole screen then the user cant see the video.

https://github.com/jwplayer/jwplayer-android-best-practice-apps/assets/139813594/9bdf4171-fd42-4237-b8ea-8151a6f1a174

**Comment by Jmilham21** [comment]
Hello, thank you for raising this issue. Though this may have been a valid issue, JW Player does not actively monitor this repository for reported issues. We require you to create a ticket following these [guidelines](https://docs.jwplayer.com/players/docs/android-troubleshooting#submit-a-support-ticket).
